### PR TITLE
Update readme with MIT license used by NATS project

### LINKED ISSUE #12: Add License

### PR DESCRIPTION
**Pull request by wallyqs**
Fixes #12

### CODE REVIEW

**Comment by tylertreat** [comment]
lgtm

**Comment by tylertreat** [comment]
Do you need to add the LICENSE file for github to pick it up?

**Comment by ColinSullivan1** [comment]
LGTM.

**Comment by wallyqs** [comment]
Right, just added the LICENSE file as well 👍

**Comment by tylertreat** [comment]
+1

**Pull request merged**
